M48
; DRILL file {KiCad 7.0.10-7.0.10~ubuntu20.04.1} date dom 18 feb 2024, 22:33:06
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-18T22:33:06+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10-7.0.10~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
%
G90
G05
T1
X6.454Y-3.6119
X6.454Y-3.9269
M30
